//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoWatch.API.Tests.Integration.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssetsMockedResponses {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetsMockedResponses() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CryptoWatch.API.Tests.Integration.Resources.AssetsMockedResponses", typeof(AssetsMockedResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UnauthenticatedAssetsDefaultListingResponse {
            get {
                return ResourceManager.GetString("UnauthenticatedAssetsDefaultListingResponse", resourceCulture);
            }
        }
        
        internal static string UnauthenticatedAssetsSpecificAmountListingResponse {
            get {
                return ResourceManager.GetString("UnauthenticatedAssetsSpecificAmountListingResponse", resourceCulture);
            }
        }
        
        internal static string AuthenticatedAssetsDefaultListingResponse {
            get {
                return ResourceManager.GetString("AuthenticatedAssetsDefaultListingResponse", resourceCulture);
            }
        }
        
        internal static string AuthenticatedAssetsDefaultSpecificAmountListingResponse {
            get {
                return ResourceManager.GetString("AuthenticatedAssetsDefaultSpecificAmountListingResponse", resourceCulture);
            }
        }
        
        internal static string AuthenticatedAssetDetailResponse {
            get {
                return ResourceManager.GetString("AuthenticatedAssetDetailResponse", resourceCulture);
            }
        }
        
        internal static string AuthenticatedAssetDetailSpecificAmountListingResponse {
            get {
                return ResourceManager.GetString("AuthenticatedAssetDetailSpecificAmountListingResponse", resourceCulture);
            }
        }
    }
}
