//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoWatch.API.Tests.Integration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarketsUnauthenticatedMockedResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarketsUnauthenticatedMockedResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoWatch.API.Tests.Integration.Resources.MarketsUnauthenticatedMockedResponses" +
                            "", typeof(MarketsUnauthenticatedMockedResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;result&quot;: [
        ///    {
        ///      &quot;id&quot;: 1,
        ///      &quot;exchange&quot;: &quot;bitfinex&quot;,
        ///      &quot;pair&quot;: &quot;btcusd&quot;,
        ///      &quot;active&quot;: true,
        ///      &quot;route&quot;: &quot;https://api.cryptowat.ch/markets/bitfinex/btcusd&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 2,
        ///      &quot;exchange&quot;: &quot;bitfinex&quot;,
        ///      &quot;pair&quot;: &quot;ltcusd&quot;,
        ///      &quot;active&quot;: true,
        ///      &quot;route&quot;: &quot;https://api.cryptowat.ch/markets/bitfinex/ltcusd&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 3,
        ///      &quot;exchange&quot;: &quot;bitfinex&quot;,
        ///      &quot;pair&quot;: &quot;ltcbtc&quot;,
        ///      &quot;active&quot;: true,
        ///      &quot;route&quot;: &quot;https://api.cryptowat. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultListingResponse {
            get {
                return ResourceManager.GetString("DefaultListingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;result&quot;: [
        ///    {
        ///      &quot;id&quot;: 3025661,
        ///      &quot;exchange&quot;: &quot;kraken&quot;,
        ///      &quot;pair&quot;: &quot;egldusd&quot;,
        ///      &quot;active&quot;: true,
        ///      &quot;route&quot;: &quot;https://api.cryptowat.ch/markets/kraken/egldusd&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 3025662,
        ///      &quot;exchange&quot;: &quot;kraken&quot;,
        ///      &quot;pair&quot;: &quot;fisusd&quot;,
        ///      &quot;active&quot;: true,
        ///      &quot;route&quot;: &quot;https://api.cryptowat.ch/markets/kraken/fisusd&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 3025663,
        ///      &quot;exchange&quot;: &quot;kraken&quot;,
        ///      &quot;pair&quot;: &quot;mxceur&quot;,
        ///      &quot;active&quot;: true,
        ///      &quot;route&quot;: &quot;https://api. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListingFromCursorResponse {
            get {
                return ResourceManager.GetString("ListingFromCursorResponse", resourceCulture);
            }
        }
    }
}
