//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoWatch.API.Tests.Integration.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarketsUnauthenticatedMockedResponses {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarketsUnauthenticatedMockedResponses() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CryptoWatch.API.Tests.Integration.Resources.MarketsUnauthenticatedMockedResponses" +
                            "", typeof(MarketsUnauthenticatedMockedResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DefaultListingResponse {
            get {
                return ResourceManager.GetString("DefaultListingResponse", resourceCulture);
            }
        }
        
        internal static string ListingFromCursorResponse {
            get {
                return ResourceManager.GetString("ListingFromCursorResponse", resourceCulture);
            }
        }
        
        internal static string ListThreeMarketsResponse {
            get {
                return ResourceManager.GetString("ListThreeMarketsResponse", resourceCulture);
            }
        }
        
        internal static string ListThreeMarketsFromCursorResponse {
            get {
                return ResourceManager.GetString("ListThreeMarketsFromCursorResponse", resourceCulture);
            }
        }
        
        internal static string PairMarketDetailResponse {
            get {
                return ResourceManager.GetString("PairMarketDetailResponse", resourceCulture);
            }
        }
        
        internal static string PairMarketPriceDetailResponse {
            get {
                return ResourceManager.GetString("PairMarketPriceDetailResponse", resourceCulture);
            }
        }
        
        internal static string MarketsPricesResponse {
            get {
                return ResourceManager.GetString("MarketsPricesResponse", resourceCulture);
            }
        }
        
        internal static string MarketsPricesWithCursorResponse {
            get {
                return ResourceManager.GetString("MarketsPricesWithCursorResponse", resourceCulture);
            }
        }
        
        internal static string MarketsPricesWithCursorAndLimitOfThreeResponse {
            get {
                return ResourceManager.GetString("MarketsPricesWithCursorAndLimitOfThreeResponse", resourceCulture);
            }
        }
    }
}
