//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoWatch.API.Tests.Integration.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarketsUnauthenticatedMockedResponses {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarketsUnauthenticatedMockedResponses() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CryptoWatch.API.Tests.Integration.Resources.MarketsUnauthenticatedMockedResponses" +
                            "", typeof(MarketsUnauthenticatedMockedResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DefaultListingResponse {
            get {
                return ResourceManager.GetString("DefaultListingResponse", resourceCulture);
            }
        }
        
        internal static string ListingFromCursorResponse {
            get {
                return ResourceManager.GetString("ListingFromCursorResponse", resourceCulture);
            }
        }
        
        internal static string ListThreeMarketsResponse {
            get {
                return ResourceManager.GetString("ListThreeMarketsResponse", resourceCulture);
            }
        }
        
        internal static string ListThreeMarketsFromCursorResponse {
            get {
                return ResourceManager.GetString("ListThreeMarketsFromCursorResponse", resourceCulture);
            }
        }
        
        internal static string PairMarketDetailResponse {
            get {
                return ResourceManager.GetString("PairMarketDetailResponse", resourceCulture);
            }
        }
        
        internal static string PairMarketPriceDetailResponse {
            get {
                return ResourceManager.GetString("PairMarketPriceDetailResponse", resourceCulture);
            }
        }
        
        internal static string MarketsPricesResponse {
            get {
                return ResourceManager.GetString("MarketsPricesResponse", resourceCulture);
            }
        }
        
        internal static string MarketsPricesWithCursorResponse {
            get {
                return ResourceManager.GetString("MarketsPricesWithCursorResponse", resourceCulture);
            }
        }
        
        internal static string MarketsPricesWithCursorAndLimitOfThreeResponse {
            get {
                return ResourceManager.GetString("MarketsPricesWithCursorAndLimitOfThreeResponse", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenMostRecentTradesResponse {
            get {
                return ResourceManager.GetString("BtcUsdKrakenMostRecentTradesResponse", resourceCulture);
            }
        }
        
        internal static string EthUsdKrakenMostRecentTradesFromCursorResponse {
            get {
                return ResourceManager.GetString("EthUsdKrakenMostRecentTradesFromCursorResponse", resourceCulture);
            }
        }
        
        internal static string EthUsdKrakenMostRecentTradesWithTimestampAndLimitResponse {
            get {
                return ResourceManager.GetString("EthUsdKrakenMostRecentTradesWithTimestampAndLimitResponse", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenSummaryResponse {
            get {
                return ResourceManager.GetString("BtcUsdKrakenSummaryResponse", resourceCulture);
            }
        }
        
        internal static string AllMarketsSummariesResponse {
            get {
                return ResourceManager.GetString("AllMarketsSummariesResponse", resourceCulture);
            }
        }
        
        internal static string AllMarketsSummariesByIdResponse {
            get {
                return ResourceManager.GetString("AllMarketsSummariesByIdResponse", resourceCulture);
            }
        }
        
        internal static string MarketsSummariesByIdFromCursorResponse {
            get {
                return ResourceManager.GetString("MarketsSummariesByIdFromCursorResponse", resourceCulture);
            }
        }
        
        internal static string MarketsSummariesByIdFromCursorWithLimitOf3Response {
            get {
                return ResourceManager.GetString("MarketsSummariesByIdFromCursorWithLimitOf3Response", resourceCulture);
            }
        }
        
        internal static string MarketsSummariesWithLimitOf3Response {
            get {
                return ResourceManager.GetString("MarketsSummariesWithLimitOf3Response", resourceCulture);
            }
        }
        
        internal static string MarketsSummariesFromCursorWithLimitOf3Response {
            get {
                return ResourceManager.GetString("MarketsSummariesFromCursorWithLimitOf3Response", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenOrderBookResponse {
            get {
                return ResourceManager.GetString("BtcUsdKrakenOrderBookResponse", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenOrderBookWithLimitOf3Response {
            get {
                return ResourceManager.GetString("BtcUsdKrakenOrderBookWithLimitOf3Response", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenOrderBookWithDepthOf60_000Response {
            get {
                return ResourceManager.GetString("BtcUsdKrakenOrderBookWithDepthOf60_000Response", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenOrderBookWithDepthOf60_000AndLimitOf7Response {
            get {
                return ResourceManager.GetString("BtcUsdKrakenOrderBookWithDepthOf60_000AndLimitOf7Response", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenOrderBookWithSpanOf0_875Response {
            get {
                return ResourceManager.GetString("BtcUsdKrakenOrderBookWithSpanOf0.875Response", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenOrderBookWithSpanOfDot875AndDepthOf13_000Response {
            get {
                return ResourceManager.GetString("BtcUsdKrakenOrderBookWithSpanOfDot875AndDepthOf13_000Response", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenOrderBookWithDepth13_000AndSpanOfDot875AndLimitOf11Response {
            get {
                return ResourceManager.GetString("BtcUsdKrakenOrderBookWithDepth13_000AndSpanOfDot875AndLimitOf11Response", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenOrderBookLiquidityResponse {
            get {
                return ResourceManager.GetString("BtcUsdKrakenOrderBookLiquidityResponse", resourceCulture);
            }
        }
        
        internal static string BtcUsdKrakenOrderBookCalculatorResponse {
            get {
                return ResourceManager.GetString("BtcUsdKrakenOrderBookCalculatorResponse", resourceCulture);
            }
        }
        
        internal static string KrakenBtcUsdOHCLResponse {
            get {
                return ResourceManager.GetString("KrakenBtcUsdOHCLResponse", resourceCulture);
            }
        }
        
        internal static string KrakenBtcUsdOHLCAfter01_01_2023Response {
            get {
                return ResourceManager.GetString("KrakenBtcUsdOHLCAfter01-01-2023Response", resourceCulture);
            }
        }
        
        internal static string KrakenBtcUsdOneMinuteOHLCAfter01_01_2023Response {
            get {
                return ResourceManager.GetString("KrakenBtcUsdOneMinuteOHLCAfter01-01-2023Response", resourceCulture);
            }
        }
        
        internal static string KrakenBtcUsdFiveMinuteOHLCResponse {
            get {
                return ResourceManager.GetString("KrakenBtcUsdFiveMinuteOHLCResponse", resourceCulture);
            }
        }
        
        internal static string KrakenBtcUsdOneHourOHLCAfter01_01_2023Before02_01_2023Response {
            get {
                return ResourceManager.GetString("KrakenBtcUsdOneHourOHLCAfter01-01-2023Before02-01-2023Response", resourceCulture);
            }
        }
        
        internal static string KrakenBtcUsdFiveMinutesAndTwoHourOHLCResponse {
            get {
                return ResourceManager.GetString("KrakenBtcUsdFiveMinutesAndTwoHourOHLCResponse", resourceCulture);
            }
        }
        
        internal static string InvalidTimeFrameKrakenBtcUsdOHLCResponse {
            get {
                return ResourceManager.GetString("InvalidTimeFrameKrakenBtcUsdOHLCResponse", resourceCulture);
            }
        }
    }
}
