//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoWatch.API.Tests.Integration.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PairsMockedResponses {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PairsMockedResponses() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CryptoWatch.API.Tests.Integration.Resources.PairsMockedResponses", typeof(PairsMockedResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UnauthenticatedPairsDefaultListingResponse {
            get {
                return ResourceManager.GetString("UnauthenticatedPairsDefaultListingResponse", resourceCulture);
            }
        }
        
        internal static string UnauthenticatedPairsSpecificAmountListingResponse {
            get {
                return ResourceManager.GetString("UnauthenticatedPairsSpecificAmountListingResponse", resourceCulture);
            }
        }
        
        internal static string UnauthenticatedPairsSpecificAmountListingWithCursorResponse {
            get {
                return ResourceManager.GetString("UnauthenticatedPairsSpecificAmountListingWithCursorResponse", resourceCulture);
            }
        }
        
        internal static string UnauthenticatedPairsListingWithCursorResponse {
            get {
                return ResourceManager.GetString("UnauthenticatedPairsListingWithCursorResponse", resourceCulture);
            }
        }
    }
}
