### List every market, paginating over 20_000 items
GET https://api.cryptowat.ch/markets

### List markets from cursor
GET https://api.cryptowat.ch/markets?cursor=TF8j1fnzBNxi7bQkOQgcFb2r9X_jzp0jq8PmiYcAnGzjlUHY93Sg7AdMzlzpvQ

### List 3 markets
GET https://api.cryptowat.ch/markets?limit=3

### List 3 markets from cursor
GET https://api.cryptowat.ch/markets?limit=3&cursor=SdgMYB9J1JiK7ejL21NoCqHcRT1eb6tTAIXZ12jGbKzEiPa-xpLZOg

### Detail pair in a market
GET https://api.cryptowat.ch/markets/kraken/btcusd

### Detail pair price in a market
GET https://api.cryptowat.ch/markets/kraken/btcusd/price

### Detail prices in a market
GET https://api.cryptowat.ch/markets/prices

### Detail prices in a market with a cursor
GET https://api.cryptowat.ch/markets/prices?cursor=BDj0fwwHBUM7Rz4YNJvyhM1vMO5PyygjB-AAht0UbizZZ7_VqEB1JA

### Detail prices in a market with a cursor and a limit of 3
GET https://api.cryptowat.ch/markets/prices?cursor=BDj0fwwHBUM7Rz4YNJvyhM1vMO5PyygjB-AAht0UbizZZ7_VqEB1JA&limit=3

### Detail btcusd trades in kraken snapshot
GET https://api.cryptowat.ch/markets/kraken/btcusd/trades

### Detail ethbtc trades in kraken snapshot from timestamp
GET https://api.cryptowat.ch/markets/kraken/ethbtc/trades?since=1690337054

### Detail ethbtc trades in kraken snapshot from timestamp with limit of 3
GET https://api.cryptowat.ch/markets/kraken/ethusd/trades?since=1690337054&limit=5

### Detail btcusd summary in kraken snapshot
GET https://api.cryptowat.ch/markets/kraken/btcusd/summary

### Detail all sumaries
GET https://api.cryptowat.ch/markets/summaries

### Detail sumaries with limit of 3
GET https://api.cryptowat.ch/markets/summaries?limit=3

### Detail sumaries from cursor with limit of 3
GET https://api.cryptowat.ch/markets/summaries?cursor=jYWBofYi7AbqxVQyHC3GQoguYnxKEL2vjPxTCJ3SAZEcXdzN6HDnSw&limit=3

### Detail sumaries from cursor with limit of 3
GET https://api.cryptowat.ch/markets/summaries?cursor=gCLPH49ToTXjmDnq2VyXCtu5HtSV__AiJU7XjdF1hAwu48pFj0_G70zdGrrKvg&
    limit=3

### Detail all sumaries by key
GET https://api.cryptowat.ch/markets/summaries?keyBy=id

### Detail sumaries by key from cursor
GET https://api.cryptowat.ch/markets/summaries?keyBy=id&
    cursor=gCLPH49ToTXjmDnq2VyXCtu5HtSV__AiJU7XjdF1hAwu48pFj0_G70zdGrrKvg

### Detail sumaries by key from cursor with limit of 3
GET https://api.cryptowat.ch/markets/summaries?keyBy=id&
    cursor=gCLPH49ToTXjmDnq2VyXCtu5HtSV__AiJU7XjdF1hAwu48pFj0_G70zdGrrKvg&limit=3
